name: simple_counter
description: "A simple counter with minimum and maximum value to increased/decreased."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  intl: ^0.19.0
  rename: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/png/app_icon.png
  remove_alpha_ios: true
  linux:
    generate: true
  macos:
    generate: true
  web:
    generate: true
  windows:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/background_image.png
    - assets/images/png/app_icon.png
